server.port=8080
server.error.include-message=always

spring.datasource.url=jdbc:postgresql://35.238.165.15:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
